### PR TITLE
Allowing to restore courses while keeping the original course id

### PR DESCRIPTION
**Pull request by joelschmid91**
A new setting was implemented in order to keep the original course id, this will also help reducing the backup size (automated course backup).

### CODE REVIEW

**Comment by adpe** [comment]
Hello @Kathrin84 

What about these changes? We have your Sandbox plugin in use and we have these changes under productive environment.

Best regards
Adrian

**Comment by abias** [comment]
Hi Adrian,

please see my comment on #2 from some days ago. We are currently working on our large backlog of plugin updates and will finally review the pull request for the 3.4 upgrade. Sorry for the delay.

Thanks,
Alex

**Comment by abias** [comment]
Hi,

it took me ages to come back to this pull request, but I have finally had a look at it.

As I had to do some cleanup of your patch, I wasn't able to merge your pull request directly, but I picked your changes and added credits to CHANGES.md. The feature is now part of the master branch (see https://github.com/moodleuulm/moodle-local_sandbox/commit/12fa4245d37f9077f8a293d2c5e63617803a60ce) and will be released to the Moodle plugin repo quite soon.

Thanks,
Alex

**Comment by adpe** [comment]
Hello @abias 

Glad to hear that you found time earlier to work on this point. Does there is a chance to get this changes also for moodle 3.3.x?

This would be nice, because our platform runs still 5 months on this version.

Greets
Adrian

**Comment by abias** [comment]
Hi Adrian,

unfortunately, we don't maintain multiple plugin versions due to our limited time. This is described in https://github.com/moodleuulm/moodle-local_sandbox#moodle-release-support.

The integrated code does the same as the code which you submitted in your pull request. So, if you have the submitted code already in production, I would recommend to keep it running until you upgrade to 3.4.

https://github.com/moodleuulm/moodle-local_sandbox#moodle-release-support also states that you could try to run the latest plugin version in a legacy Moodle version. In this particular case, I can't recommend this as I migrated the sandbox files from Moodledata to a Moodle filearea in the 3.4 version and you would have to be really careful to backport this to 3.3.

Sorry, 
Alex

**Pull request closed without merging**
